import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import SignIn from '@/pages/SignIn'
import LandingPage from '@/components/LandingPage'
import SignUp from '../components/Register'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

<LandingPage/>

{/* <SignUp/> */}

    </>
  )
}
